FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Streamlit muss auf Port 80 laufen
EXPOSE 80

CMD ["streamlit", "run", "streamlit_app.py", "--server.port", "80", "--server.address", "0.0.0.0"]
