[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
loglevel=info

[program:backend]
command=streamlit run /app/backend/app.py --server.port 8501 --server.address 0.0.0.0
directory=/app/backend
autostart=true
autorestart=true
stdout_logfile=/var/log/backend.log
stderr_logfile=/var/log/backend_err.log

[program:frontend]
command=python /app/frontend/app.py
directory=/app/frontend
autostart=true
autorestart=true
stdout_logfile=/var/log/frontend.log
stderr_logfile=/var/log/frontend_err.log
