name: Build and Push Docker to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Schritt 0: Repository auschecken
      - uses: actions/checkout@v3

      # Schritt 1: Azure Login mit Secret
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS4 }}

      # Schritt 2: ACR Login über Azure CLI
      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.AZURE_ACR_NAME }}

      # Schritt 3: Docker Image bauen
      - name: Build Docker image
        run: docker build -t ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/maria-ai:latest .

      # Schritt 4: Docker Image pushen
      - name: Push Docker image to ACR
        run: docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/maria-ai:latest
